---
title: "Air quality advisories"

listing:
  - id: aq-statements
    template: _aqs_listing.ejs
    contents:
      - ./_recent_statements.yaml
    sort: "date desc"
  - id: ssb
    template: _ssb_listing.ejs
    contents:
      - ./_ssb.yaml
    sort: "date desc"
---

## Issued advisories

::: {#aq-statements}
:::


## Current Smoky Skies Bulletin map

::: {#ssb}
:::

## Latest updates

For the latest updates:

- Subscribe to the [Air Quality Subscription Service](https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/air-advisories/air-quality-subscription-service)
- Outside regular business hours, visit [Environment and Climate Change Canada’s Public Weather Alerts for B.C.](https://weather.gc.ca/?province=bc&zoom=5&alertTableFilterProv=BC)
- For **Metro Vancouver** and the **Fraser Valley Regional District**, see [Metro Vancouver’s Air Quality Data and Advisories](https://metrovancouver.org/services/air-quality-climate-action/air-quality-data-and-advisories) and [AirMap.ca](https://gis.metrovancouver.org/maps/Air). For subscription to air quality advisories and bulletins, use [Metro Vancouver’s Air Quality and Climate Change Mailing List](https://metrovancouver.org/services/air-quality-climate-action/mailing-list).

## About air quality advisories

An air quality advisory is issued when pollutant concentrations approach or exceed predetermined limits, or when degraded-air-quality episodes are expected to continue or worsen.

Advisories are issued in order to:

- inform about degraded air quality
- help people make informed choices about reducing their exposure to elevated concentrations of air pollutants
- affect emission reduction actions (such as a limit on industrial emissions or wood stove use)
- provide vulnerable individuals and the general public with health advice developed by BC health agencies


## About Smoky Skies Bulletins

The Smoky Skies Bulletin is a special type of public advisory to communicate the rapidly changing nature of wildfire smoke. It is issued when areas of the province are being impacted or have reasonable potential to be impacted by wildfire smoke within 24 to 48 hours. These bulletins are based on available pollutant concentrations information, satellite information, smoke forecast models and visual observations, and are not intended to manage local emission sources.
