---
title: "Smokey Skies Bulletin"
location: "Elkford"
date: 2024-08-21
ssb: true
categories:
author:
  - name: FName LName
    title: Senior Air Quality Meteorologist
    phone: 250-645-9358
---

[PDF](2024-08-21-smoky-skies-issue.pdf)
[HTML](2024-08-21-smoky-skies-issue.html)

The Regions of BC highlighted on the map are being impacted or are likely to be impacted by wildfire smoke over the next 24-48 hours.

Local smoke near active wildfires. Smoke levels vary across the southern half of the province because of localized rain and changing wind conditions.

The next bulletin update will be available July 26, 2024.

The bulletin can be accessed online at [gov.bc.ca/airqualityadvisories](https://www.gov.bc.ca/airqualityadvisories).

## Be informed

During a wildfire, smoke conditions can change quickly over short distances and can vary considerably hour-by-hour.

Wildfire smoke is a natural part of our environment but it is important to be mindful that exposure to smoke may affect your health.

People with pre-existing health conditions, respiratory infections such as COVID-19, older adults, pregnant women and infants, children, and sensitive individuals are more likely to experience health effects from smoke exposure.

## During smoky conditions

**Follow your common sense**

- Stop or reduce your activity level if breathing becomes uncomfortable or you feel unwell.
- Stay cool and drink plenty of fluids.
- If you have asthma or other chronic illness, carry any rescue (fast-acting) medications with you at all times and activate your personal care plan that has been designed with your family physician.
- Make sure that children and others who cannot care for themselves follow the same advice.

**Monitor your symptoms**

- People respond differently to smoke. Mild irritation and discomfort are common, and usually disappear when the smoke clears.
- If you are unsure whether you need medical care, call HealthLink BC at 8-1-1.
- If you are experiencing difficulty in breathing, chest pain or discomfort, or a severe cough, contact your health care provider, walk-in clinic, or emergency department. If you are having a medical emergency, call 9-1-1.

**Tips to reduce your smoke exposure**

- Smoke levels may be lower indoors but will still be elevated, so stay aware of your symptoms even when you are indoors.
- Running a commercially available HEPA (high efficiency particulate air) filter can improve indoor air quality in the room where the device is located.
- If you have a forced air heating/cooling system in your home, it may help to change the
filter and set the fan to run continuously.
- Reduce indoor air pollution sources such as smoking, burning incense, and frying foods.
- Consider going to a library, community center, or shopping mall with cooler filtered air to get some relief from the smoke.
- If travelling in a car with air conditioning, keep the windows up and the ventilation set to recirculate.
- If you are very sensitive to smoke, consider moving to another location with cleaner air, but be aware that conditions can change rapidly.
- Maintaining good overall health is a good way to prevent health effects resulting from short-term exposure to air pollution.

## More information

**For additional general information about wildfire smoke and air quality:**

**For additional general information about wildfire smoke and your health:**

## Contact information

**Media and public inquiries regarding air quality and this bulletin:**

{{< meta contact.1.name >}}, {{< meta contact.1.title >}}, {{< meta contact.1.phone >}}

**Media questions regarding health implications of wildfires:**

## Regions included under this bulletin

**B.C. North Peace River** includes the City of Fort St John and all communities along Hwy 97 extending from Farmington to Pink Mountain; Hwy 29 including Moberly Lake, Hudson’s Hope; also includes Rolla, Clayhurst and Goodlow.

**B.C. South Peace River** includes Chetwynd, Dawson Creek, Pouce Coupe, and Tumbler Ridge.

**Stuart - Nechako** includes Fraser Lake, Fort Fraser, Vanderhoof, Fort St James, and Tachie.

**Williston** includes McLeod Lake, Mackenzie and Williston Lake.
